# .streamlit/config.toml

[theme]
# 强制使用浅色主题
base = "light"
primaryColor = "#0078D7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"

[browser]
# 禁用收集使用统计
gatherUsageStats = false

[server]
# 服务器配置
headless = true
enableCORS = false
enableXsrfProtection = true

[global]
# 禁用文件监控以避免 inotify 限制问题
developmentMode = false

[runner]
# 禁用自动重新运行
fastReruns = false
